### ISSUE TITLE
Swagger support

### ISSUE THREAD

**Issue by NolanRogers** [zowe/zlux#159]
What this is
Have zlux host swagger files provided by apps

Support swagger that is either yaml or json

**Comment by 1000TurquoisePogs** [comment]
Present in staging, should be in 1.4.0
App writers can now include JSON or YAML format Swagger 2.0 files, each having the same name as the App's REST dataservice names, within their app's /doc/swagger folder so that developers can reference these swagger documents at runtime via a new App route: /ZLUX/plugins/PLUGINID/catalogs/swagger
Individual services can be viewed via: /ZLUX/plugins/PLUGINID/catalogs/swagger/SERVICENAME

Even if swagger documents are not present, the server will still show some default values via contextual knowledge.
