### ISSUE TITLE
nodeServer.sh tail error

### ISSUE THREAD

**Issue by fbeyl** [zowe/zlux#198]
tail command in nodeServer.sh and zssserver.sh not working on linux (mint). Purpose is to keep last 5 (or x) logfiles this needs the option -n in the tail command otherwise no logfiles are deleted.
 
>  for f in `ls -r -1 $ZLUX_NODE_LOG_DIR/nodeServer-*.log 2>/dev/null | tail  +$ZLUX_NODE_LOGS_TO_KEEP

should be:
  
  for f in `ls -r -1 $ZLUX_NODE_LOG_DIR/nodeServer-*.log 2>/dev/null | tail -n +$ZLUX_NODE_LOGS_TO_KEEP`

**Comment by 1000TurquoisePogs** [comment]
I looked to fix this but it appears outdated behavior of tail.
On both a z/OS 3.1 system and an Ubuntu 22 system, tail with or without `-n` does the same thing.
I suspect there was some old version of tail which had a difference in behavior.
I can't find info about it and do not want to change something that has been otherwise stable, so I will close this unless it is reproducible and an issue still today.
