### ISSUE TITLE
Add option to start Zowe plugin in full screen

### ISSUE THREAD

**Issue by TRechkalov-RS** [zowe/zlux#257]
As far I understand I need to fill defaultWindowStyle to set plugin window size.
I want to start plugin application in full screen because my application has no much sense without it.
It will be very useful to configure initial window size as "full screen".

Info from documentation:
https://docs.zowe.org/stable/extend/extend-desktop/mvd-plugindefandstruct.html#application-web-content-attributes

**Comment by NolanRogers** [comment]
Thank you for raising this issue. I have moved it into the backlog and the team will review it.

**Comment by NakulManchanda** [comment]
Since, zowe 1.5.0 we have this feature to open app in new browser tab.
This is Single App Mode, and you can try it on existing apps like editor
![image.png](https://images.zenhubusercontent.com/5cacf8caef5a5209eacab3ea/c2864085-f991-4d36-bcbc-7216690024c9)

Before zowe-1.5.0 its just manual, you can open your app in single app by providing plugin id in url:
https://my.mainframe.com:8544/ZLUX/plugins/org.zowe.zlux.bootstrap/web/index.html?pluginId=org.zowe.editor&showLogin=1

**Comment by DivergentEuropeans** [comment]
Hey @TRechkalov-RS

As @NakulManchanda stated, we have our standalone/single app mode already pre-built. Is that what you were looking for, or were you referring to starting the app in maximized view, but still within the desktop? Or were you referring to making start in standalone by default without the user-defined option

**Comment by TRechkalov-RS** [comment]
Hi @DivergentEuropeans 

I was not looking for "open in new browser tab" option.
I looked for starting the app in maximized view within the desktop.
I was not looking for "making start in standalone..."

For your information "open in new browser tab" is not working with iframe applications.

**Comment by DivergentEuropeans** [comment]
Iframe applications didn't work at one point, but they should have been fixed with the latest code. Are you running the latest 'staging' branch for **zlux-app-manager**? 


And ah okay, thanks for clarifying that. Yes, you can start the app in maximized mode. What you'd want to do is maximize the app upon initialization. 

1. import `Angular2InjectionTokens `from `'pluginlib/inject-resources'`
2. within the constructor of your app, in the arguments, do
`@Optional() @Inject(Angular2InjectionTokens.WINDOW_ACTIONS) private windowActions: Angular2PluginWindowActions`
3. then, inside the constructor, check that window actions exist and then execute the action
```
if (this.windowActions) {
   this.windowActions.maximize();
}
```

Within existing code, take a look at a usage of it here in the File Explorer widget for the Code Editor app:
1) https://github.com/zowe/zlux-file-explorer/blob/acdfd046d54af1c70e66ae67f378348d6620ce48/src/app/components/filebrowseruss/filebrowseruss.component.ts#L30
2) https://github.com/zowe/zlux-file-explorer/blob/acdfd046d54af1c70e66ae67f378348d6620ce48/src/app/components/filebrowseruss/filebrowseruss.component.ts#L82
3) https://github.com/zowe/zlux-file-explorer/blob/acdfd046d54af1c70e66ae67f378348d6620ce48/src/app/components/filebrowseruss/filebrowseruss.component.ts#L310 

(In this example, window actions are being used when a node is right clicked)
Let me know if this is what you wanted

**Comment by TRechkalov-RS** [comment]
@DivergentEuropeans right now I use 'master' branch for zlux-app-manager.
Our application is an iframe plugin. Is your maximize Angular2 instruction applicable for this case?

**Comment by DivergentEuropeans** [comment]
@TRechkalov-RS Hey, I apologize for the slow reply I missed this.

Yes, it now is (mostly)! Iframes as of two weeks ago now have the ability to use window events as well with the help of an Iframe adapter we created. Before I continue, I'd highly recommend using the most up to date features which will always be in the **staging** branch. The features here are typically safe for use and go into prod on average a couple weeks after. 

For Iframes how the instructions would change:
Obviously, no Angular injection tokens here, Iframe doesn't have that. Instead, we'd want to

1. Import the Iframe adapter script, example here:
`<script type="text/javascript" src="../../../org.zowe.zlux.bootstrap/web/iframe-adapter.js"></script>`
https://github.com/zowe/sample-iframe-app/blob/872250fef8c5ab779b4294c6501a358d482f3e05/web/html/index.html#L30

(You'll see right above that line is a way to import the use of our Zowe logger too, so currently we have two Iframe scripts for Zowe things)

2. Use window events like so: 
`await windowActions.minimize();`
https://github.com/zowe/sample-iframe-app/blob/872250fef8c5ab779b4294c6501a358d482f3e05/web/html/index.html#L173

**Comment by DivergentEuropeans** [comment]
Hey @TRechkalov-RS 

Just checking in that the windowActions.maximize( ) worked for you for your Iframe application. Otherwise, we'll assume that it's fixed and close this ticket

**Comment by TRechkalov-RS** [comment]
Unfortunatelly I can't check it in production code. But I made a proof of concept check and it works. Thank you)

**Comment by NolanRogers** [comment]
Closing as fixed thanks
