### ISSUE TITLE
Performance: Reduce initial load time & in app performance

### ISSUE THREAD

**Issue by NakulManchanda** [zowe/zlux#271]
1) Explorer takes some time to load and show login poup and then show loading circle beofre it loads tree, investigate if it can be improved, if not how we can enhance to user experience, so user don't have to keep looking at white screen.

2) We need abort unnecessary network request 
   if user close tab in multi tab app - jes
   if user change filter - in all explorers
   if users change selection in single file apps - mvs and uss

**Comment by NakulManchanda** [comment]
Lot of work done to improve the load time.
Explorer ui server is re-written 
 - caching files on first ever request till zowe is up
 - sending comprresed aap.js - 1.5MB to 420 KB - so faster download on client side

Still to improve:
 
![image](https://user-images.githubusercontent.com/4791635/86812993-a61aa400-c04d-11ea-9d3d-8408cf5f71b0.png)

**Comment by NakulManchanda** [comment]
https://github.com/zowe/zlux/issues/486

**Comment by NakulManchanda** [comment]
https://github.com/zowe/zlux/issues/358

**Comment by NakulManchanda** [comment]
USS /MVS - debounce function to rate limit on typeahead search, or increase debounce rate if exists already

**Comment by AdarshdeepCheema** [comment]
As out priority now is explorer-JES only (explorer USS and explorer MVS functionality can be achieved by zowe desktop editor) and explorer-JES is moved to zOSMF APIs, we tried using the API as below:
atlasFetch(zosmf/restjobs/jobs/${encodeURLComponent(jobName)}/${jobId}/files/${fileId}/records,
{ credentials: 'include', headers: { 'X-CSRF-ZOSMF-HEADER': '*', 'X-IBM-Record-Range': ${startLine}- ${startLine + 50000} }})
IT TOOK 2 MINS TO GET THE FILE WITH 1000000 LINES
WHEN WE TRIED TO PICK 100000 LINES AT ONCE THEN IT TOOK 58 SECS
WITHOUT USING X-IBM-Record-Range, AND FETCHING THE FILE ALL AT ONCE TAKES 35 SECS.
SO CLOSING THIS DUE TO PERFORMANCE ISSUE.
