### ISSUE TITLE
Unable to launch explorers in zLUX using Zowe 0.9.1 

### ISSUE THREAD

**Issue by NayerNajafi** [zowe/zlux#36]
Three explorers don't work via zLUX:
This message has been issued:
**Content was blocked because it was not signed by a valid security certificate**
<img width="698" alt="zlux - explorer error" src="https://user-images.githubusercontent.com/44011615/46740415-c64ae280-cc70-11e8-8277-8bbdac3cce98.PNG">

**Comment by 1000TurquoisePogs** [comment]
Which browser is this?
There is an issue that we're developing a solution for, which is that the explorers come from another server than the desktop, and the combination of self-signed default certificates and cross-site iframe causes browsers to warn the user. Generally this warning can be dismissed in order to proceed anyway, but in the long term, we'll be removing the cross-site behavior by relying on the API mediation layer of Zowe - sometime in November/December. The certificates of Zowe, however, should be replaced with certificates signed for your group. The desktop's certificate for example, can be replaced by changing the location in this configuration file: https://github.com/zowe/zlux/wiki/Configuration-for-ZLUX-Proxy-Server-&-ZSS#https

**Comment by 1000TurquoisePogs** [comment]
@jordanCain is this still a problem or will the new use of APIML solve this once and for all?

**Comment by jordanCain** [comment]
Use of APIML should solve this if we're same origin then I don't think any browser will try to interrogate same origin certificate twice? 
It's still a problem today but the workaround is to load the explorers outside of the desktop once and add the certificate exception to their browser then and then they should launch just fine within the desktop.

**Comment by NayerNajafi** [comment]
It is not a problem now. It has been fixed by loading the explorers outside of the desktop and adding the certificate exception to the browser then they should launch just fine within the desktop. Thanks

**Comment by jordanCain** [comment]
Desktop now available via APIML in Zowe 1.3.0 so these problems will no longer crop up
