### ISSUE TITLE
Remove File's Open Tab When File Deletes

### ISSUE THREAD

**Issue by aarohimshah1** [zowe/zlux#381]
Currently, if a file tab is open and that file is deleted from the left pane, the file still remains open in the tabs.

There are 2 options:
1) When the open file is deleted, the tab with the deleted file should disappear immediately
2) When the open file is deleted, a modal should appear giving a message along the lines of, "this file cannot be deleted because it is currently open."

**Comment by DivergentEuropeans** [comment]
I like option 2, and option 2 should show up only if the tab is selected. If it's visible, but not selected, option 1 is preferred behavior

**Comment by shivanshs9** [comment]
Hey @DivergentEuropeans, I'm up for it! Just some quick questions regarding the desired behaviour.

Right now, a [delete-file-modal](https://github.com/zowe/zlux-file-explorer/blob/staging/src/app/components/delete-file-modal/delete-file-modal.component.html) component opens on choosing to delete.
**Expected behaviour:** In the case when the file to delete is open, we should either open the modal (option 2) and do not show the delete-file-modal or show the delete-file-modal and if confirmed deletion, remove the tab (option 1).

I could get the open tabs information in the zlux-editor using EditorControlService and override [this method](https://github.com/zowe/zlux-editor/blob/00f51660f9a70da253ed63e57048b288cf2900be/webClient/src/app/editor/project-tree/project-tree.component.ts#L172). However, from what I checked by browsing the code, that event isn't triggered by right-clicking the file in project tree and deleting.

I also had an additional query... Is it possible to test file creation and deletion functionality without installing ZSS? Or what can I try to properly test the behaviour on my local machine?

**Comment by DivergentEuropeans** [comment]
Hello @shivanshs9 !
Thanks for taking an interest : o

> However, from what I checked by browsing the code, that event isn't triggered by right-clicking the file in project tree and deleting.

That's correct, **that** file deletion propagates from the Editor to the File Explorer. The right click menu as you noticed happens in the File Explorer (browsing tree). The method you found gets called when we call delete from the Editor menu

![image](https://user-images.githubusercontent.com/20528015/74210839-592bd080-4c5b-11ea-8df4-fb2b052e0727.png)

> Is it possible to test file creation and deletion functionality without installing ZSS? Or what can I try to properly test the behaviour on my local machine?

Since you need authentication to see and delete files & folders, this becomes fairly challenging to test without zss-auth. I'd recommend reaching out to @1000TurquoisePogs or @struga0258 to see if we have test systems in place, available to the public, for people to try out but I don't think we do unfortunately...

That being said, code-wise it's not an incredibly difficult challenge. If you do end up creating a PR for this, ping me! and I'll try it on my local machine and report back if it works OK

**Comment by shivanshs9** [comment]
@DivergentEuropeans thanks for the help!
I did notice that event is triggered from the menu bar, but couldn't find it being triggered from the right click context menu in the zlux-file-explorer.
And I did try out the original functionality in a remote system provided by Zowe trial. But since I can't try out any changes in that installed software, it'll be a great help if you could try out the changes. 

I should be able to roll out a PR today to fix this, so meanwhile could you please assign me this issue?

**Comment by shivanshs9** [comment]
@DivergentEuropeans, I've developed a new modal component for option 2. As for automatically removing tab on success deletion, there's no way to observe whether the deletion call was a success or not. I'll have to change the code in [zlux-file-explorer](https://github.com/shivanshs9/zlux-file-explorer/blob/40cf37b6c1abeb690c9f0aa676e8719d557660f0/src/app/components/filebrowseruss/filebrowseruss.component.ts#L675) to return the Observable so I could subscribe to its updates.

Since the code would span two separate GitHub repos, do I need to create two Github PRs and link them to this issue?

**Comment by DivergentEuropeans** [comment]
Yes, if the solution requires both the File Explorer and Code Editor, then you'll need two PRs

**Comment by shivanshs9** [comment]
@DivergentEuropeans I've submitted two PRs. Can you please review it?

**Comment by DivergentEuropeans** [comment]
Done in V2
