### ISSUE TITLE
zLUX requires certain levels of node

### ISSUE THREAD

**Issue by stevenhorsman** [zowe/zlux#397]
@jthyssenrocket commented on [Fri Feb 14 2020](https://github.com/zowe/zowe-install-packaging/issues/1098)

zLUX requires certain levels of Node.

Examples:
6.14.3 does not work
6.17.0 works
8.16.0 works
8.16.1 does not work
8.16.2 works

The installation script should verify that the version of node installed is supported

**Comment by grlwholifts** [comment]
Hi, i would like to take this up!

**Comment by 1000TurquoisePogs** [comment]
@grlwholifts sure! Two places to try this:
https://github.com/zowe/zowe-install-packaging/blob/master/install/zowe-check-prereqs.sh

and

https://github.com/zowe/zlux-app-server/blob/master/bin/app-server.sh

You can already see a trick for checking versions here: https://github.com/zowe/zlux-app-server/blob/master/bin/app-server.sh#L39
So, why not apply that trick to these files to check before installing (validate) and at runtime (app-server)

**Comment by grlwholifts** [comment]
Hey @1000TurquoisePogs i wrote a sample script, which i think would work in both `zlux-app-server` as well as `zowe-check-prereqs`. I will integrate it into the files you mentioned. Till then, could you let me know if I'm understanding the objective well?

```
allowed_versions=("v6.17.0" "v8.16.0" "v8.16.2")
# "8.16.1" "6.14.3"

if test $(which node); then
  node_version_current="$(node --version)"
else
  node_version_current="Node is not installed OR it's not in executable path."
fi

if [[ " ${allowed_versions[@]} " =~ " ${node_version_current} " ]]; then
  echo "Yay, zLUX is supported on your current Node version :)"
else
  printf "\e[1;31mERROR:\e[0m\e[97m zLUX is not supported on your current Node ($node_version_current) version!\e[0m\n";
  printf "\e[97m Current supported versions are: ${allowed_versions[*]}\e[0m\n";  
fi

```

**Comment by 1000TurquoisePogs** [comment]
Thanks for asking @grlwholifts 
This would work for identifying 8.16.1, but a different approach is needed to identify ranges of versions to make sure that it is going to give a warning only when it is a specifically bad version.

Because, we support 6.14.4+ except 8.16.1 so far.
So that means you need to check if you have v6 or v8, then if you have above 6.14.4, and either below 8.16.1 or above 8.16.1
But, we also support v12. So far we support every version of v12.

In the previous code you can see we use the "cut" command to get different parts of the version:
```
nodeVersion="$(${NODE_BIN} --version)"
nodeMajorVersion=$(echo ${nodeVersion} | cut -c2-3)
if [ $nodeMajorVersion = "12" ]
```

So you would need minor & patch portions too in order to see if you had something below 6.14.4.

**Comment by grlwholifts** [comment]
Hi @1000TurquoisePogs i wrote this following script and it correctly identifies the version demarcations. I am thinking of injecting it below the declaration for NODE_BIN or assigning it to path in both the files mentioned above. Let me know what you think about this code so that I can work further.

```
nodeVersion="$(${NODE_BIN} --version)"
nodeMajorVersion=$(echo ${nodeVersion} | cut -d '.' -f 1 | cut -d 'v' -f 2)
nodeMidVersion=$(echo ${nodeVersion} | cut -d '.' -f 2)
nodeLastVersion=$(echo ${nodeVersion} | cut -d '.' -f 3)
##echo $nodeMajorVersion.$nodeBeechVersion.$nodeLastVersion

if [[ $nodeMajorVersion -eq 12 ]]
then
	echo "Version 12"
elif [[ $nodeMajorVersion -eq 8 ]] && [[ $nodeMidVersion -ne 16 ]] || [[ $nodeLastVersion -ne 1 ]]
then 
	echo "Below 8.16.1 OR above 8.16.1"
elif [[ $nodeMajorVersion -eq 6 ]] && [[ $nodeMidVersion -ge 14 ]]
then
	if [[ $nodeLastVersion -gt 4 ]] || [[ $nodeMidVersion -ne 14 ]]
	then
		echo "Above 6.14.4"
	fi
fi

```

**Comment by 1000TurquoisePogs** [comment]
Closing this because all versions of node specified are out of support, and zowe v2 does such checks now within zwe.
