### ISSUE TITLE
Sample react-app

### ISSUE THREAD

**Issue by dbaldon** [zowe/zlux#405]
This `Note: This App requires the Sample Angular App to be installed.` is stated on the README.md page for the Sample react-app. There is no explanation given and I wasn't able to find the reason by looking at the source. Can the README.md be updated to explain the requirement or at least explain it here in this Issue?

**Comment by 1000TurquoisePogs** [comment]
Good point!
Yes, I will do that.
The reason is because for demonstration purposes the other "sample" apps use an import-type dataset, here: https://github.com/zowe/sample-react-app/blob/master/pluginDefinition.json#L23

Import means "attach this logic to more than one URL" so that more than one plugin can make use of the same code.
If the react app had that code instead of using an import, there would be no need for you to install both.
A little more info here: https://github.com/zowe/zlux/wiki/ZLUX-Dataservices
