### ISSUE TITLE
[SPIKE] Research benefit of YML vs JSON vs ENV for Zowe instance config

### ISSUE THREAD

**Issue by timgerstel** [zowe/zlux#455]
Is the current instance.env file the best way to configure a Zowe instance? The current file essentially acts as a shell script and just loads environment variables.
Consider (credit: @stevenhorsman ):
![image.png](https://images.zenhubusercontent.com/5d0799a241e1974be7393ed7/f74a2d16-c65c-4e6e-bb28-4be32df29a21)

Potential issues:
How to read arrays/objects into env vars that can be communicated between instance and components.

**Comment by 1000TurquoisePogs** [comment]
I have a feeling that mainframe sysadmins will not understand how yaml works. It took me a while to understand it, so I don't want to add that as part of the learning curve.
JSON is a little easier to understand, but it has several issues:
{ } [ ] don't show up correctly on 3270 if the codepage is different, which is confusing
JSON doesnt allow comments (though, json5 does, if it was used across-the-board)

And then there's environment variables, which are just the worst because the key value can only be [A-Za-z0-9_] which is too limited to make rich statements about certain things.

**Comment by 1000TurquoisePogs** [comment]
If we don't map the content of these files into environment variables, then we will be creating a breaking change for anything that depends on environment variables for configuration.

So, we should make a json(or yaml)-to-envvar mapper.
i have an envvar to json mapper, here, so we can make one in reverse: https://github.com/zowe/zlux-server-framework/pull/230
