### ISSUE TITLE
Can not pin or unpin apps to taskbar

### ISSUE THREAD

**Issue by CindyZX** [zowe/zlux#56]
This problem is found on Zowe 1127 daily build. Zowe 0.9.3 does not have this problem
Reproduce steps:
1.login to MVD
2.click toolbox in the bottom left, right click an app and select "Pin to taskbar", nothing happens, expected behavior is that the app is pinned to taskbar
3.on the taskbar, right click an app, select "Unpin from taskbar", nothing happens, expected behavior is that, the app is unpinned from taskbar

**Comment by 1000TurquoisePogs** [comment]
Works for me on 0.9.4, but, can you check for network activity? You would have an HTTP PUT that responds with a 201 when successful
![image](https://user-images.githubusercontent.com/30730276/49534922-d35f0900-f890-11e8-8671-ae20b6e21531.png)
If this is not the case, it could be due to filesystem permissions. Every user that uses zowe should be in the same zowe user group, because files and folders are created within the https://github.com/zowe/zlux/wiki/Configuration-Dataservice based on filesystem permissions.

**Comment by jackjia-ibm** [comment]
This should have been fixed by https://github.com/zowe/zowe-install-packaging/pull/181.
