### ISSUE TITLE
Special characters or wrong label in the jobname

### ISSUE THREAD

**Issue by Martin-Zeithaml** [zowe/zlux#564]
There are these issues:
1. Special character ```#``` in the job name will cause, that the job files are not accessible.
1. Job name with unsupported characters will cause the same.

See example: 
1. Jobname ```AAAAAAAA``` exceeded the length for the job name (JCL error), but the job files are accessible, you can get the error code and resolve the problem.
1. Jobname ```#``` is fine, was successfully executed, but the job files are not accessible.
1. Jobname ```?``` contains unsupported character in the job name, but the job files are not accessible and you can't resolve the problem (Note: the original job name was ```!```, but unsupported character was replaced with ```?```).

![image](https://user-images.githubusercontent.com/66114686/101948323-1d062b00-3bf2-11eb-97e9-d40aeae1470e.png)

**Comment by NakulManchanda** [comment]
we have simillar issue filed and attempted earlier

**Comment by NakulManchanda** [comment]
Old MVS Issue: https://github.com/zowe/zlux/issues/428

Main reason:
Explorers forward all request to z/OSMF via APIML
That use to break.
Needs to verify again if PR https://github.com/zowe/api-layer/pull/746 fix the issue for MVS. 
if yes, need similar setting for jobs api

Attempted PR: 
https://github.com/zowe/explorer-mvs/pull/127
https://github.com/zowe/api-layer/pull/746
Close Reason:  
https://github.com/zowe/api-layer/issues/716

**Comment by AdarshdeepCheema** [comment]
@Martin-Zeithaml  
Regarding `Jobname AAAAAAAA exceeded the length for the job name (JCL error), but the job files are accessible, you can get the error code and resolve the problem.
` : This seems like the design and expected behaviour from JES side
And for:
`Jobname ? contains unsupported character in the job name, but the job files are not accessible and you can't resolve the problem (Note: the original job name was !, but unsupported character was replaced with ?).` : this seems like the JES2 issue/ or Design, where it return the ? instead of special character
We are unable to access such JOBs in the JES explorer, because the zOSMF APIs do not like the '?' in the JOBNAME and throws the 400 error. I will try to reach out to zOSMF team to verify.
![image](https://user-images.githubusercontent.com/57364561/166748532-cef578f3-29e4-48fb-8ba9-9cf454ab6a40.png)

FYI: if you try the JES3 instead of JES2 then specify the special character in the JOBNAME in JCL then JES3 will return a random JOBNAME and will not replace the special character with '?' in the JOBNAME.
<img width="1472" alt="Screen Shot 2022-05-04 at 1 51 32 PM" src="https://user-images.githubusercontent.com/57364561/166749154-4f31f702-4d87-495e-8a5c-343e75c5869f.png">
FYI: @Joe-Winchester  @joepun76

**Comment by AdarshdeepCheema** [comment]
Talked to the zOSMF Team and they said  '?' is not valid for a JOBNAME as per https://www.ibm.com/docs/en/zos/2.5.0?topic=d-name-field-5.
But somehow the JES2 gives us the '?' in the JOBNAME for special character. In SDSF we can access such job and its files without issue, but not with zOSMF APIs. 
JES3 seems to have to have the fix or workaround for it, where JES3 will generate a valid and random JOBNAME, when in a JCL, the JOBNAME has special character.

**Comment by Martin-Zeithaml** [comment]
Closing this issue, let's discuss this in only #820.
