### ISSUE TITLE
Invalid record for dataset because EOL is \r 

### ISSUE THREAD

**Issue by John-A-Davies** [zowe/zlux#577]
In the file editor, I got "Invalid record for dataset, recordLength=130" but max for dataset is 80 (is this because \r is not counted as newline, so the whole file appears as a single line?)

We'd have to try out entering file data where the EOL has various values.  A user could paste a file from the clipboard, and that might come from a system where the EOL is different from the EOL the ZLUX editor is expecting.

**Comment by 1000TurquoisePogs** [comment]
How did that dataset appear in ISPF?
One thing we can't currently handle is undefined-length datasets, which should be treated as one long line, but just fails.
In this case however, it sounds like there's a bug in ZSS's `fread`?
Because, what ZSS will do is figure out the lrecl, and then read that much at a time, and send an array where each entry is a record. Could be the translation of the array of records into the form of a text buffer in monaco resulted in 2 records being joined into 1 line, thus causing an error when trying to write back.

**Comment by DivergentEuropeans** [comment]
I was not able to replicate this issue. Many bugs came up and many of them got solved, but this specifically I could not replicate
