### ISSUE TITLE
Does ZOWE support z/OS ZIIP processors ?

### ISSUE THREAD

**Issue by F-LEMANER** [zowe/zlux#591]
Hello,
Does ZOWE supports the ZIIP processors ?
Usage of ZIIP allows to reduce the cost of cpu usage.

See https://en.wikipedia.org/wiki/ZIIP

Best regards

**Comment by 1000TurquoisePogs** [comment]
Yes and no.
The parts of Zowe that can run on z/OS are divided by language: C, Java, NodeJS.
Only the Java code is ZIIP enabled, which means the API Mediation Layer composed of the API Gateway, Discovery, and Catalog servers along with any Java-based services that work with them such as the Jobs and Datasets servers.

Likewise, the CLI and VSCode Explorer make large use of z/OSMF, which is Java and therefore also ZIIP enabled.

The nodeJS code is not ZIIP enabled, BUT, we have a tech preview available currently that allows you to run all of the java code, and all of the nodejs code, on linux or zlinux via Docker. So, that would be an even bigger cost & cpu savings, because the code would not be running under z/OS. In that circumstance, only the C code remains on z/OS, which is not ZIIP enabled, but that solution does greatly reduce the footprint of Zowe on z/OS.

You can see a comparison between the two on our documenation at https://docs.zowe.org/stable/getting-started/zowe-architecture.html#zowe-architecture-when-using-docker-image which also shows which portions are Java (ZIIP enabled) and everything else.

If you would like to try the tech preview of Docker, you can find it at https://www.zowe.org/download.html and we'd love to hear your feedback if you do.
