### ISSUE TITLE
zlux-app-server Installation Readme dosent work

### ISSUE THREAD

**Issue by Cieronpowell** [zowe/zlux#758]
The Readme at https://github.com/zowe/zlux-app-server dosent work, when following step by step (on Mac & Linux environment). I think its something to do with the server.json config file being different? (error is its looking for an agent  port / ip which isnt configured, as it dosent tell you to / how).

Any chance the docs could be updated, I spent some time looking through the source, but really am struggling to figure out how to get the thing going (ideally without ZSS as I dont have a Z environment to hand to play with).

Thanks
Cieron

**Comment by 1000TurquoisePogs** [comment]
Which error do you get specifically?
Step 7 of the readme is optional, only for people with Z access. It deals with "agent". ZSS is an agent.
https://github.com/zowe/zlux-app-server#agent-setup-app-server-side
https://github.com/zowe/zlux/wiki/Configuration-for-ZLUX-App-Server-&-ZSS#zss-configuration

The intent is for this not to be required. Perhaps there's a regression we can pinpoint from the error you see though.

Also of note is that we have a mock server for ZSS, so that you'd be able to work with the app-server closer to what people see when they have a Z environment. The mock server is just a simple python server, so you could try it out: https://github.com/zowe/zss/tree/staging/mock

**Comment by Cieronpowell** [comment]
Thanks for the quick reply the error is actually back on step 3 initial start up. It's throwing out ZWED5006W, but continues then eventually fails in utility.Js because port is not defined. 

I will grab / upload the full logs when I'm back on my pc tomorrow.

From what I can tell the default server.json is wrong, it contains the agent section but without a host/ port section. this is what causes the above error code.

Strangely though if I try to remove this section entirely because I don't want ZSS anyway (either from the workspace/serverConfig folder or defaults) it seems to ignore it and Carries on using the agent config from somewhere (I've been through all the files it outputs and it dosent match any of them) 

Like I say, will upload the logs tomorrow as I'm sure it makes a lot more sense to you guys that it does me.

Thanks
Cieron.

**Comment by Cieronpowell** [comment]
Ive bunged the complete logs on pastebin. This is an example straight after completing the initial build.

https://pastebin.com/tCW49fyf

**Comment by 1000TurquoisePogs** [comment]
Hello again and thanks for proving all this info. I was able to reproduce it and make some fixes that I think are appropriate for the dev environment scenario. These will go into the staging branch first, meaning they wont reach the "master" branch until the next release, 1.26, which is in December. Due to this, you may want to switch to the staging branches meanwhile or just patch the changes in from the linked PRs.

**Comment by Cieronpowell** [comment]
Thanks for looking at this / resolving the issue, I am now able to get the default config working using the new PR. 

Thanks
Cieron
