### ISSUE TITLE
Access to Dataservice (SAF Profiles) does not work even tough access to ZLUX.** is granted

### ISSUE THREAD

**Issue by lv198** [zowe/zlux#770]
**Describe the bug**
I followed the guide of "Advanced Zowe configuration" -> "Controlling access to dataservices".
I cannot do anything within Zowe Web Interface even though I granted ACCESS(UPDATE) to ZLUX.** profile for my User-ID.

I get the following message in the DEBUG-Log from ZWESISTC:
ZWES0100I in authServiceFunction, parm = 0x23978                                                                                             
ZWES0100I handleEntityCheck(): user = MYUSER, entity = ZLUX.0.CFG.ORG_ZOWE_ZLUX_NG2DESKTOP.GET.USER.PLUGINDATA.APP, class = ZOWE, access = 2
ZWES0100I safVerify(VERIFY_CREATE) safStatus = 0, RACF RC = 0, RSN = 0, ACEE=0x7EE9B818                                                      
ZWES0100I safAuth safStatus = 4, RACF RC = 4, RSN = 0, ACEE=0x7EE9B818                                                                       
ZWES0100I safVerify(VERIFY_DELETE) safStatus = 0, RACF RC = 0, RSN = 0, ACEE=0x7EE9B818                                                      
ZWES0100I handleEntityCheck() done                                                                                                           

What is to do that SAF Profiles work properly? When I disable "RBAC", everything is just fine.

**Comment by 1000TurquoisePogs** [comment]
@struga0258 can you compare the results here versus the tests you have on RBAC?

**Comment by struga0258** [comment]
After taking a look at this it seems like something was done when configuring the ZOWE class. Have you checked to see if the class is active or no? I have run into this issue before where the class is configured but not active and it gives the same error. The error also indicates that the class may not be RACLISTed, so that is another thing that i would check. Please read use this doc to see if you missed something https://docs.zowe.org/stable/user-guide/mvd-configuration/#defining-the-racf-zowe-class. Another thing that I would point out is that when you add a member to the class, you must refresh the class or else it doesn't update, ex: `"SETROPTS GENERIC(ZOWE) REFRESH"`. Last thing I would do is make sure that access UPDATE gives READ access, essentially all you need for rbac is READ access.

**Comment by lv198** [comment]
@struga0258 sorry for the delayed answer, I didn't get a notification... I followed all the steps mentioned in the doc and also refreshed the class, did not help. I only created the profile ZLUX.** and gave my User-ID access to it (first I had UPDATE, then READ but there's no difference).

Is there something else I could have done wrong or that I could check to solve this?

**Comment by lv198** [comment]
Hi @struga0258 @1000TurquoisePogs 
It seems like the application can't handle generic profile like ZLUX.**
I just created the explicit profile ZLUX.0.COR.GET.PLUGINS in Class ZOWE, permitted myself with Read on it and now I get (only for that profile):

`safAuth safStatus = 0, RACF RC = 0, RSN = 0, ACEE=0x7F4D64D0`

which looks good for me. For all other profiles that should be handled with ZLUX.**, I still get

`safAuth safStatus = 4, RACF RC = 4, RSN = 0, ACEE=0x7F4D64D0`

What could be the problem that it doesn't work with ZLUX.**?

**Comment by lv198** [comment]
Okay, I found the problem and I think that could be an enhancement for documentation. You have to set class Zowe as "generic" first **before** you create generic profiles in it. So, after creating CDT ZOWE, just issue "SETROPTS GENERIC(ZOWE) REFRESH" and you're fine. Then, you can create generic profiles as you want.

**Comment by 1000TurquoisePogs** [comment]
Great, thanks for letting us know, this wasn't clear to me either so I opened up a documentation request ticket on it. https://github.com/zowe/docs-site/issues/2207
