### ISSUE TITLE
Zowe Desktop: SSL TN3270 Sessions Issues

### ISSUE THREAD

**Issue by grewaljasi** [zowe/zlux#806]
Hi, I would like to know, if zowe supports SSL TN3270 connections as I am experiencing problems connecting as TLS Session.
We are running with Zowe : v. 1.26.0+20211206

We can establish sessions to these systems using :
Mocha as SSL connection 
PComm:  Enable Security: Yes
Microsoft CryptoAPI 
TLS1.2

I see the following in ZWESVSTC Log:
2022-03-07 15:34:50.366 <ZWED:66235> ZWESVUSR INFO (org.zowe.terminal.proxy:tn3270data,terminalProxy.js:762) ZWED0106I 
- Saw Websocket request, method=GET
2022-03-07 15:34:50.588 <ZWED:66235> ZWESVUSR WARN (org.zowe.terminal.proxy:tn3270data,terminalProxy.js:588) ZWED0140W 
- [Host=169.10.244.214, Port=997, ClientIP=169.13.40.232] Host communication error=1920407009073561601:error:1425F102:
SSL routines:ssl_choose_client_version:unsupported protocol:../deps/openssl/openssl/ssl/statem/statem_lib.c:1958:

Any information would be appreciated.
Thank You in advance,
Regards,
Jasi Grewal.

**Comment by 1000TurquoisePogs** [comment]
Can you confirm your connection really is TLS 1.2?

TLS can support downgrade to allow a client to connect to a server that does not support the requested version, such as if you wanted TLS 1.2 but the server only offered TLS 1.1

However, every part of Zowe only supports TLS 1.2 minimum, so if the server actually was something below 1.2, you would see this error.

**Comment by grewaljasi** [comment]
Hi, On PCOM session, we use option TLS 1.2 and on our host, we have the following configured for TN3270:
TELNETPARMS                                                        
    SECUREPORT 997                ; PORT 992 SUPPORTS NATIVE TLS   
    CONNTYPE SECURE               ; Support SSL                    
    KEYRING SAF TCPIP/HISDKEYRING ; Keyring shared by servers      
    CLIENTAUTH NONE               ; Client Certificate none        
    ENCRYPT SSL_DES_SHA           ; Ciphers used                   
            SSL_3DES_SHA                                           
            SSL_AES_256_SHA                                        
            SSL_AES_128_SHA                                        
    ENDENCRYPT 

Please advise, what else I should check.
Thank You in advance and for the response,
Regards,
Jasi.

**Comment by 1000TurquoisePogs** [comment]
This configuration seems fine but I'd like to know what PCOMM says about the session when it successfully establishes the connection, such as which cipher it ended up using, and which level of TLS. I'm not a pcom expert so I'm not sure which button if any can be clicked to see that info... I think it has a lock icon that may display it, as I've seen in some other terminals.
But, it's possible Zowe's settings are too strict, and they are configurable but it's not intuitive or documented because changing the security is not something we'd usually suggest https://github.com/zowe/zlux-server-framework/blob/v1.x/staging/lib/webserver.js#L329-L330
This might be better handled in a short screen-share meeting if possible. This group does have weekly calls at 9am EST every friday if you'd like to join in, or we could set something up.

**Comment by grewaljasi** [comment]
Hi, Thank You for the response and you are correct that it is using TLS 1.0 and I would have to investigate how to upgrade the TLS 1.0 to minimum TLS 1.2.
Here's what I received from Pcom active session:
Security Protocol: TLS 1.0
TLS_RSA_WITH_3DES_EDE_CBC_SHA

Thank You again,

**Comment by grewaljasi** [comment]
Thank you for your support and I will close this case for now and work in upgrading the TN3270 TLS.
