### ISSUE TITLE
JES Explorer character encoding issue with national characters

### ISSUE THREAD

**Issue by lnlyssg** [zowe/zlux#820]
I'm working on a UK based LPAR running Zowe, we frequently use the # character as a suffix for jobnames but these cannot be opened from JES Explorer, for example trying to open a job named JOBNM# results in an error message:

`No match for method GET and pathInfo='JOBNM'`

If I change the # to a @ I _can_ open this in JES Explorer. If I include the # in the middle of the job i.e. JOB#NM the message becomes:

`No match for method GET and pathInfo='JOB' `

I see similar issues when using the "£" national character, this displays as a "?" in JES Explorer and  cannot be opened. For reference z/OSMF allows me to open all output in Job Output but the "£" shows as a "?"

This seems like it may be similar to #300

**Comment by 1000TurquoisePogs** [comment]
@Joe-Winchester is in the same area so I imagine he may have seen this too, but I've also assigned @AdarshdeepCheema since he volunteered to check it out. Thanks!

**Comment by AdarshdeepCheema** [comment]
@jaytay79  can you please clarify the statement` I see similar issues when using the "£" national character, this displays as a "?" in JES Explorer and cannot be opened. For reference z/OSMF allows me to open all output in Job Output but the "£" shows as a "?"`

Did you mean that '£' is shown as '?' in JOB TREE, OR when '£' is shown as '?' when we open a job file in JES?

PLEASE add screenshots if possible

**Comment by lnlyssg** [comment]
This is what happens:
![image](https://user-images.githubusercontent.com/10902647/166508464-ef027a42-1bc7-42e8-9995-1934f1b19763.png)

**Comment by Martin-Zeithaml** [comment]
Same as #564.

**Comment by AdarshdeepCheema** [comment]
Talked to the zOSMF Team and they said  '?' is not valid for a JOBNAME as per https://www.ibm.com/docs/en/zos/2.5.0?topic=d-name-field-5.
But somehow the JES2 gives us the '?' in the JOBNAME for special character. In SDSF we can access such job and its files without issue, but not with zOSMF APIs. 
JES3 seems to have to have the fix or workaround for it, where JES3 will generate a valid and random JOBNAME, when in a JCL, the JOBNAME has special character.

**Comment by Martin-Zeithaml** [comment]
z/OS JES2 -> z/OS JES2 Initialization and Tuning Reference -> [JOBDEF - Job Definition](https://www.ibm.com/docs/en/zos/2.5.0?topic=definition-parameter-description-jobdef) -> BAD_JOBNAME_CHAR

**BAD_JOBNAME_CHAR**=c|?
Specifies the character to use in place of invalid characters in a jobname. This translation is used for JES2 commands and displays RACF® entity names too. Valid values are: **A-Z,0-9, $, #, @, /, +, :, ?, _, -, !**
Modification: $T JOBDEF operator command or JES2 cold start

The question mark is the default, that's why we are seeing it on our system. But we have to expect anything from the valid values, I suppose that for example slash is troublemaker too.

**Comment by AdarshdeepCheema** [comment]
@Martin-Zeithaml  yes I verified that '?' is the default replacement for an invalid character
I believe https://www.ibm.com/docs/en/zos/2.5.0?topic=d-name-field-5 is the correct doc regarding the JOBNAME and the https://www.ibm.com/docs/en/zos/2.5.0?topic=definition-parameter-description-jobdef is outdated or incorrect. the only valid values are` A-Z,0-9, $, #, @ ` and  `/, +, :, ?, _, -, ! `are all getting converted into '?' in JES2

FYI: I am working with zOSMF team to log an APAR where we cannot access the JOB via zOSMF APIs where JOBNAME has '?' in it.

**Comment by Martin-Zeithaml** [comment]
There is a small misunderstanding, JOBDEF is not outdated or incorrect, this is a parameter for JES2 to set which character will be displayed instead of bad one. 
JCL jobname valid values are ```A-Z,0-9, $, #, @```, no doubt, but you can submit anything and on the system, where JES2 was customized and ```BAD_JOBNAME_CHAR``` was used, we can expect any replacement char from this set: ```/, +, :, ?, _, -, !```.

Try the command ```$D JOBDEF```, you will see something like:
```
JOBDEF  ACCTFLD=OPTIONAL,BAD_JOBNAME_CHAR=?,...
```

That's why we see ```?``` on our system, because the ```JOBDEF BAD_JOBNAME_CHAR``` is using the default (question mark).

But we have to expect also the other possible characters.

**Comment by AdarshdeepCheema** [comment]
got u, Thanks for the clarification. I will convey this info to zOSMF

**Comment by AdarshdeepCheema** [comment]
zOSMF will take care of the special character issue. Closing this defect.
I will add the info regarding tracking the zOSMF progress on this issue, If I get anything from them.
