### ISSUE TITLE
JCL syntax highlighting could use some work

### ISSUE THREAD

**Issue by DivergentEuropeans** [zowe/zlux#839]
JCL syntax highlighting could use some work

Use ISPF for reference but if possible, check that ISPF does it right. ISPF may not do everything 100% correctly

![image.png](https://images.zenhubusercontent.com/5cf465968d690c7080bd33a8/132db61b-c1d7-4746-a40b-3eb852281e83)

(ignore the red box - focus on different coloring highlighting in between screenshots)

**Comment by Martin-Zeithaml** [comment]
Is this all for the JCL hiliting?
```zlux-editor/webClient/src/app/editor/code-editor/monaco/hiliters/jcl.ts```
I can try to look into this.

**Comment by 1000TurquoisePogs** [comment]
That's the main file, the only other thing I see is theme rules: https://github.com/zowe/zlux-editor/blob/v2.x/staging/webClient/src/app/editor/code-editor/monaco/monaco.config.ts#L70-L87=

**Comment by 1000TurquoisePogs** [comment]
Once you have changes ready to test, I could always test them against the JCL on my machine.

**Comment by 1000TurquoisePogs** [comment]
The logic for the highlighting is here https://microsoft.github.io/monaco-editor/monarch.html

**Comment by 1000TurquoisePogs** [comment]
@lchudinov may know if monaco allows syntax highlighting by means other than 'monarch' as monarch has limitations in its regex-and-state method and jcl is a very positional language. Unsure if monarch is the optimal way to do this.

**Comment by Martin-Zeithaml** [comment]
I see there 2 major problems, which I am not solving now:
1. Comment continuation - you need to check if there is non-blank char in column 72 and then continue with the comment on the following line (empty line is valid continuation comment)
2. DLM for in-stream data - if you specify DLM, you need to know the value of DLM to be able to correctly mark the end of data

At this point, I am focusing on simple problems. Based on the regexes used and small experience, good testing scenario is to copy each JCL in 4 variants:
1. Line is terminated in the end
2. Line has 1 space before the termination
3. Line has more spaces before the termination
4. Line has versioning number

It is shown on this example, that syntax depends on the line ending (something was already fixed in the monaco playground):

![image](https://user-images.githubusercontent.com/66114686/170446140-dea1b771-6f95-4c4d-a999-0a4e41e0f417.png)

**Comment by Martin-Zeithaml** [comment]
For testing use this repo: [Martin-Zeithaml/jclMonarch](https://github.com/Martin-Zeithaml/jclMonarch).
I will appreciate any JCL examples.

**Comment by Martin-Zeithaml** [comment]
Current state of JCL syntax highlighter was improved, however there is still a room for improvement. If a major problem will be found, new issue should be opened.
