### ISSUE TITLE
ZSS APIs fails to get content of Datasets

### ISSUE THREAD

**Issue by AdarshdeepCheema** [zowe/zlux#859]
ZSS APIs fails to get content of Datasets, where Dataset is load modules output of programs after compile and linkedit
Steps to reproduce:
1. compile and link-edit a program to produce a load
2. try to open it in Editor and you will get 400 error with response "Undefined-length dataset"
3. this same dataset can be opened in MVS explorer that uses zOSMF API.
Screenshots
![Screen Shot 2022-06-13 at 12 10 45 PM](https://user-images.githubusercontent.com/57364561/173397754-10d24555-0063-40b8-a6a6-0092e213e4dc.png)
 r below

**Comment by 1000TurquoisePogs** [comment]
The editor doesnt show undefined-length datasets by design, because they're likely to be binary files that have no reason to be viewed or edited in an editor. Certainly, they're useful to do file transfer operations on though.
We should at least improve the error message: the editor doesnt tell you the reason why it doesnt open is that it's an undefined-length dataset.
Any opinions from anyone on whether we should display undefined length, and to what extent?

Also, why do we see 4 requests? I wonder if there's a retry bug.
