### ISSUE TITLE
Yaml file is open in UTF-8 no matter how tag is set

### ISSUE THREAD

**Issue by Martin-Zeithaml** [zowe/zlux#950]
**Describe the bug**

1. Open yaml file in zowe editor.
2. UTF-8 garbage is displayed.

**Expected behavior**
Readable text is displayed.

**Additional context**
Files in runtime, no change done to ```example-zowe.yaml```, ```example-zowe.txt``` is a copy of yaml file:
```
/zowe/runtime/v2.4.0: ls -T
- untagged    T=off DEVELOPERS.md
- untagged    T=off README.md
                    bin
                    components
- untagged    T=off example-zowe.txt      (just a copy with different extension)
- untagged    T=off example-zowe.yaml
                    files
                    fingerprint
                    licenses
- untagged    T=off manifest.json
                    schemas
```
```Example-zowe.txt``` is opened as expected:
![image](https://user-images.githubusercontent.com/66114686/204315725-a7ba3b6c-e645-42c8-9ed7-9fbdc1c46d2d.png)

```Example-zowe.yaml``` is opened in UTF-8:
![image](https://user-images.githubusercontent.com/66114686/204315908-432f9556-4665-4769-9d22-0b30d54c1315.png)

Tag to ISO or UTF-8 does not help.
No problems with other file types.

Do I have some setting wrong?
Any idea?

**Comment by 1000TurquoisePogs** [comment]
The file appears to be EBCDIC since it is readable when untagged.
So, tagging it as EBCDIC is the correct tag. Tagging it as ISO would be opposite, and tagging as UTF8 never works (IBM advises against it in the BPKX AUTOCVT documentation)

ZSS assumes encoding when untagged according to file extension. So, it's not certain to succeed, it is just opinionated.

**Comment by Martin-Zeithaml** [comment]
Yes, EBCDIC works.
It is just little bit confusing.
