### ISSUE TITLE
Upgrade bluebird to 3.7.2

### ISSUE THREAD

**Issue by balhar-jakub** [zowe/zlux#991]

**Comment by 1000TurquoisePogs** [comment]
This looks easy to do.
I'd rather move away from bluebird entirely, but that is harder to do because of our use of `Promise.coroutine`

**Comment by DivergentEuropeans** [comment]
So I did a bit of research on this @1000TurquoisePogs . Promises were introduced in ES6, we are in ES5. I didn't upgrade ES version during the Webpack upgrade because Webpack is supposed to be JS-version agnostic, so it didn't come up in on my radar. But we certainly could. Promise.coroutine is achieved via async/await, which was introduced in ES8. So my opinion is it's okay to remove Bluebird eventually, but it's still highly performant so we shouldn't unless we upgrade to ES8 at least, preferably newer
